spring :
  cloud:
    config:
      enabled: false
  application:
    name: User Registration Service
  data :
    mongodb:
      uri: mongodb+srv://myAtlasDBUser:Tw26FBfrN3cqIq5X@myatlasclusteredu.igregay.mongodb.net/sample_training?retryWrites=true&w=majority
      database: sample_training
server:
  port: 8080

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/


logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            driver: DEBUG
            core:
              MongoTemplate: DEBUG


